const SeriesArray = [
   {
    'Title': 'Breaking Bad',
    'imdbRating': 9.5,
    'Genre': 'Crime, Drama, Thriller',
    'Plot': `A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future.`,
    'Director': 'Vince Gilligan',
    'Actors': 'Bryan Cranston, Aaron Paul, Anna Gunn, Betsy Brandt',
    'Year': '2008 – 2013',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BYmQ4YWMxYjUtNjZmYi00MDQ1LWFjMjMtNjA5ZDdiYjdiODU5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg',
   },
   {
    'Title': 'Game of Thrones',
    'imdbRating': 9.2,
    'Genre': 'Action, Adventure, Drama',
    'Plot': `Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for a millennia.`,
    'Director': 'Mark Mylod and More',
    'Actors': 'Emilia Clarke, Peter Dinklage, Kit Harington, Lena Headey',
    'Year': '2011 – 2019',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg',
   }, 
   {
    'Title': 'The Wonder Years',
    'imdbRating': 8.4,
    'Genre': 'Comedy, Drama, Family',
    'Plot': `Kevin Arnold recalls growing up during the late 60s and early 70s; the turbulent social times make the transition from child to adult unusually interesting.`,
    'Director': 'Carol Black',
    'Actors': 'Fred Savage, Dan Lauria, Alley Mills, Jason Hervey',
    'Year': '1988 – 1993',
    'Poster': 'srcset="https://m.media-amazon.com/images/M/MV5BMWRhYjZjOTQtOGNiNC00MTQ0LWE2MTYtMTQxYzEwNDE3NjYyXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UY447_.jpg 319w, https://m.media-amazon.com/images/M/MV5BMWRhYjZjOTQtOGNiNC00MTQ0LWE2MTYtMTQxYzEwNDE3NjYyXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UY670_.jpg 479w, https://m.media-amazon.com/images/M/MV5BMWRhYjZjOTQtOGNiNC00MTQ0LWE2MTYtMTQxYzEwNDE3NjYyXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UY337_.jpg 241w, https://m.media-amazon.com/images/M/MV5BMWRhYjZjOTQtOGNiNC00MTQ0LWE2MTYtMTQxYzEwNDE3NjYyXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX724_.jpg 724w, https://m.media-amazon.com/images/M/MV5BMWRhYjZjOTQtOGNiNC00MTQ0LWE2MTYtMTQxYzEwNDE3NjYyXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UY1012_.jpg 724w"',
   }, 
   {
    'Title': 'Aspirants',
    'imdbRating': 9.2,
    'Genre': 'Drama',
    'Plot': `It is the story of the journey of three UPSC (public service competitive exams in India) aspirants and their friendship against all odds.`,
    'Director': 'Arunabh Kumar',
    'Actors': 'Naveen Kasturia, Shivankit Singh Parihar, Abhilash Thapliyal, Sunny Hinduja',
    'Year': '2021 - ?',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BYWIzMDEyOTItNzA0OC00YmU1LTk3OWUtNjM4ZmE4ZDcyNWZmXkEyXkFqcGdeQXVyMTExMTIzMTA5._V1_.jpg',
   }, 
   {
    'Title': 'Sherlock',
    'imdbRating': 9.1,
    'Genre': 'Crime, Drama, Mystery',
    'Plot': `The quirky spin on Conan Doyle's iconic sleuth pitches him as a "high-functioning sociopath" in modern-day London. Assisting him in his investigations: Afghanistan War vet John Watson, who's introduced to Holmes by a mutual acquaintance.`,
    'Director': 'Paul McGuigan',
    'Actors': 'Benedict Cumberbatch, Martin Freeman, Una Stubbs, Rupert Graves',
    'Year': '2010 – 2017',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BMWEzNTFlMTQtMzhjOS00MzQ1LWJjNjgtY2RhMjFhYjQwYjIzXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_.jpg',
   }, 
   {
    'Title': 'House of Cards',
    'imdbRating': 8.6,
    'Genre': 'Drama',
    'Plot': `The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.`,
    'Director': 'David Fincher',
    'Actors': 'Kevin Spacey, Michel Gill, Robin Wright, Kate Mara',
    'Year': '2013 – 2018',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BNmM4ODU1MzItODYyYi00Y2U0LWFjZjItYTRhZWIwOGMyZTRhXkEyXkFqcGdeQXVyNjc2NTQ4Nzk@._V1_.jpg',
   }, 
   {
    'Title': 'Westworld ',
    'imdbRating': 8.5,
    'Genre': 'Drama, Mystery, Sci-Fi',
    'Plot': `At the intersection of the near future and the reimagined past, waits a world in which every human appetite can be indulged without consequence.`,
    'Director': 'Lisa Joy',
    'Actors': 'Evan Rachel Wood, Jeffrey Wright, Ed Harris, Thandiwe Newton',
    'Year': '2016 – 2022',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BZDg1OWRiMTktZDdiNy00NTZlLTg2Y2EtNWRiMTcxMGE5YTUxXkEyXkFqcGdeQXVyMTM2MDY0OTYx._V1_.jpg',
   }, 
   {
    'Title': 'Stranger Things',
    'imdbRating': 8.7,
    'Genre': 'Drama, Fantasy, Horror',
    'Plot': `When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.`,
    'Director': 'Matt Duffer',
    'Actors': 'Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour',
    'Year': '2016 – 2025',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BNWZmYzVjZjktNzQ4ZC00MDUwLTkzYTktNzMxMzViZjBlNDk4XkEyXkFqcGdeQXVyODExNTExMTM@._V1_.jpg',
   }, 
   {
    'Title': 'Better Call Saul',
    'imdbRating': 9,
    'Genre': 'Crime, Drama',
    'Plot': `The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman.`,
    'Director': 'Vince Gilligan',
    'Actors': 'Bob Odenkirk, Rhea Seehorn, Jonathan Banks, Patrick Fabian',
    'Year': '2015 – 2022',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BZDA4YmE0OTYtMmRmNS00Mzk2LTlhM2MtNjk4NzBjZGE1MmIyXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg',
   }, 
   {
    'Title': 'Narcos (I)',
    'imdbRating': 8.8,
    'Genre': 'Biography, Crime, Drama',
    'Plot': `A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.`,
    'Director': 'Carlo Bernard',
    'Actors': 'Pedro Pascal, Wagner Moura, Boyd Holbrook, Alberto Ammann',
    'Year': '2015 - 2017',
    'Poster': 'https://m.media-amazon.com/images/M/MV5BNmFjODU3YzgtMGUwNC00ZGI3LWFkZjQtMjkxZDc3NmQ1MzcyXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg',
   }, 
   
]

export default SeriesArray;